language: python
addons:
  apt:
    update: true
sudo: false
cache: pip
git:
  depth: false

python:
  - 2.7

script:
  - BRZ_PLUGINS_AT=debian@$(pwd) brz plugins -v
  - BRZ_PLUGINS_AT=debian@$(pwd) python -Werror -Wignore::ImportWarning -Wignore::PendingDeprecationWarning -Wignore::DeprecationWarning $(which brz) selftest --parallel=fork

install:
  - sudo apt install python-all-dev subunit python-debian python-apt python-testtools patchutils pristine-tar devscripts python-lzma libalgorithm-merge-perl python-distro-info quilt
  - travis_retry pip install -U setuptools
  - travis_retry pip install -U pip coverage codecov flake8 testtools paramiko fastimport configobj cython testscenarios six docutils python-subunit dulwich bzr+lp:brz

after_success:
  - codecov
